///uiz_animation_setFunction(id,x,y,width,height,alpha,time)
with(argument0){
function_x=argument1
function_y=argument2
function_w=argument3
function_h=argument4
function_a=argument5
function_time=argument6
}
