///uiz_drawdslist_setscrollbar(instanceid,scrollbarwidth[0.16],scrollbarwidthtype[dp],scrollbarsprite[spr_uiZ_scrollbar],scrollbarbacktexmode[uiz_texturemode_fill],scrollbarAnimationTime[0.2],scrollbarAnimation[uiz_smoothstep],scrollspeed[100])
gml_pragma("forceinline");
argument0.scrollbarwidth=argument1;
argument0.scrollbarwidthtype=argument2;
argument0.scrollbarsprite=argument3;
argument0.scrollbarbacktexmode=argument4;
argument0.scrollbarAnimationTime=argument5;
argument0.scrollbarAnimation=argument6;
argument0.scrollspeed=argument7;
