///uiz_margin(instanceid,left,lefttype,right,righttype,top,toptype,bottom,bottomtype)
gml_pragma("forceinline");
argument0.leftmargin=argument0
argument0.leftmargintype=argument1
argument0.rightmargin=argument2
argument0.rightmargintype=argument3
argument0.topmargin=argument4
argument0.topmargintype=argument5
argument0.bottommargin=argument6
argument0.bottommargintype=argument7
