///uiz_stringbox_numberCounter_setButtonStyle(instanceid,minButtonColor[c_white],minButtonOnColor[c_white],minButtonOverColor[c_white],minButtonAlpha[c_white],maxButtonSprite[spr_uiZ_plus],maxButtonColor[c_white],maxButtonOnColor[c_white],maxButtonOverColor[c_white],maxButtonAlpha[c_white])
gml_pragma("forceinline");
argument0.numberCounter_minButtonSprite=argument1;
argument0.numberCounter_minButtonColor=argument2;
argument0.numberCounter_minButtonOnColor=argument3;
argument0.numberCounter_minButtonOverColor=argument4;
argument0.numberCounter_minButtonAlpha=argument5;
argument0.numberCounter_maxButtonSprite=argument6;
argument0.numberCounter_maxButtonColor=argument7;
argument0.numberCounter_maxButtonOnColor=argument8;
argument0.numberCounter_maxButtonOverColor=argument9;
argument0.numberCounter_maxButtonAlpha=argument10;


