///uiz_margin(instanceid,left,lefttype,right,righttype,top,toptype,bottom,bottomtype)
gml_pragma("forceinline");
argument0.leftmargin=argument1
argument0.leftmargintype=argument2
argument0.rightmargin=argument3
argument0.rightmargintype=argument4
argument0.topmargin=argument5
argument0.topmargintype=argument6
argument0.bottommargin=argument7
argument0.bottommargintype=argument8
