value=string_copy(value,1,selpmin)+string_copy(value,selpmax+1,len-selpmax);
pos=selpmin
hasselection=0
selp1=0
selp2=0
selpmin=0
selpmax=0
selpminline=0
selpmaxline=0
selpxmin=0;
selpxmax=0;
len=string_length(value)
uiz_textarea_resetpos()
