uiz_animation_capture_oldstate(id)
posinframex=uiz_static;
posinframey=uiz_static;
uiz_window_fixbackground();
uiz_fix_Base_endmargin();
width=bars*5+end_leftframemargin+end_rightframemargin;
height=end_topframemargin+end_bottomframemargin;
x=an_old_x;
y=an_old_y;
setpointx=uiz_auto;
setpointy=uiz_auto;
sizestatus=0
uiz_fixwindowpos_finalValues();
uiz_animation_capture_newstate(id)
uiz_animation_setFunction(id,maximizeanimation,maximizeanimation,maximizeanimation,maximizeanimation,uiz_one,maximizeanimationspeed)
uiz_animation_start(id)
