///uiz_huesquare_setvalues(instanceid,h,s,v)
with(argument0){
h=argument1
//inh=argument1
//fromh=argument1
s=argument2
//ins=argument2
//froms=argument2
v=argument3
//inv=argument3
//fromv=argument3
}
