function macros() {
#macro dp 1
#macro dpmin 1.1
#macro fc 2
#macro fcm 2.3
#macro fcmax 2.5
#macro fcmin 2.4
#macro fcx 2.1
#macro fcy 2.2
#macro px 0
#macro pxmin 0.1
#macro uiz_acceldecel 23
#macro uiz_animationtype_multi 1
#macro uiz_animationtype_single 0
#macro uiz_anticipate_in 28
#macro uiz_anticipate_inout 30
#macro uiz_anticipate_out 29
#macro uiz_anticipate_outin 31
#macro uiz_auto -1
#macro uiz_bottom 1
#macro uiz_bounce_in 24
#macro uiz_bounce_inout 26
#macro uiz_bounce_out 25
#macro uiz_bounce_outin 27
#macro uiz_center 8
#macro uiz_circular_in 13
#macro uiz_circular_inout 15
#macro uiz_circular_out 14
#macro uiz_circular_outin 16
#macro uiz_cubic_in 17
#macro uiz_cubic_inout 19
#macro uiz_cubic_out 18
#macro uiz_cubic_outin 20
#macro uiz_elastic_in 33
#macro uiz_elastic_inout 35
#macro uiz_elastic_out 34
#macro uiz_elastic_outin 36
#macro uiz_exponential_in 9
#macro uiz_exponential_inout 11
#macro uiz_exponential_out 10
#macro uiz_exponential_outin 12
#macro uiz_fill 9
#macro uiz_gray 15132390
#macro uiz_horizontal 0
#macro uiz_left 0
#macro uiz_middle 0.5
#macro uiz_mouseclick 2
#macro uiz_mouseover 1
#macro uiz_mousepressed 3
#macro uiz_mousereleased 4
#macro uiz_nocontain 0
#macro uiz_nomouse 0
#macro uiz_nonpos 4
#macro uiz_one 37
#macro uiz_parentcontain 1
#macro uiz_quadratic_in 1
#macro uiz_quadratic_inout 3
#macro uiz_quadratic_out 2
#macro uiz_quadratic_outin 4
#macro uiz_right 1
#macro uiz_screencontain 2
#macro uiz_sin_in 5
#macro uiz_sin_inout 7
#macro uiz_sin_out 6
#macro uiz_sin_outin 8
#macro uiz_smoothstep 21
#macro uiz_snapbottom 6
#macro uiz_snapleft 7
#macro uiz_snapright 5
#macro uiz_snaptop 4
#macro uiz_spring 22
#macro uiz_stack 10
#macro uiz_static 11
#macro uiz_straight 0
#macro uiz_texturemode_fill 0
#macro uiz_texturemode_tile 1
#macro uiz_texturemode_fill_edgeless 3
#macro uiz_texturemode_tilefit 2
#macro uiz_top 0
#macro uiz_vertical 1
#macro uiz_wigle 32
#macro uiz_zero 38
#macro xtra 3
#macro uiz_null -1
#macro uiz_window_contain_none 0
#macro uiz_window_contain_corner 1
#macro uiz_window_contain_topbar 2
#macro uiz_window_contain_window 3
#macro uiz_xml_headTag 0
#macro uiz_xml_headAttributeTag 1
#macro uiz_xml_dataTag 2
#macro uiz_xml_dataTagWithAttributes 3
#macro uiz_xml_attributeName 4
#macro uiz_xml_attributeData 5
#macro uiz_xml_closingTag 7
#macro uiz_treelist_boxState_noBox 0
#macro uiz_treelist_boxState_collapsed 1
#macro uiz_treelist_boxState_extended 2
#macro uiz_gridlist_selection_none 0
#macro uiz_gridlist_selection_cell 1
#macro uiz_gridlist_selection_row 2
#macro uiz_gridlist_selection_column 3



}
